- subtitle: データベース RDF 化支援ツール
  sub_list:
    - id: D2RQ
      url: http://d2rq.dbcls.jp/
      image_source: img/service_assets/D2RQ_Mapper.png
      description:
    - id: TogoDB
      url: http://togodb.org/
      image_source: img/service_assets/TogoDB.svg
      description:
- subtitle: 知識の抽出および RDF 化支援ツール
  sub_list:
    - id: PubAnnotation
      url: http://pubannotation.org/
      image_source: img/service_assets/PubAnnotation.png
      description:
    - id: TextAE
      url: http://textae.pubannotation.org/
      image_source: img/service_assets/TextAE.png
      description:
    - id: PubDictionaries
      url: http://pubdictionaries.org
      image_source: img/service_assets/PubDictionaries.png
      description:
    - id: Allie
      url: http://allie.dbcls.jp/
      image_source: img/service_assets/Allie.png
      description:
    - id: Colil
      url: http://colil.dbcls.jp/
      image_source: img/service_assets/Colil.png
      description:
    - id: inMeXes
      url: https://docman.dbcls.jp/im/
      image_source: img/service_assets/inMeXes.png
      description:
    - id: OntoFinder
      url: http://ontofinder.dbcls.jp/
      image_source: img/service_assets/ontofinder.png
      description:
