- subtitle_jp: データベース RDF 化支援ツール
  subtitle_en: Support tools for RDFization of databases
  sub_list:
    - id: D2RQ
      url: http://d2rq.dbcls.jp/
      image_source: img/service_assets/D2RQ_Mapper.png
      description_jp:
      description_en:
    - id: TogoDB
      url: http://togodb.org/
      image_source: img/service_assets/TogoDB.svg
      description_jp:
      description_en:
- subtitle_jp: 知識の抽出および RDF 化支援ツール
  subtitle_en: Suport tools for knowledge extraction and RDFization
  sub_list:
    - id: PubAnnotation
      url: http://pubannotation.org/
      image_source: img/service_assets/PubAnnotation.png
      description_jp:
      description_en:
    - id: TextAE
      url: http://textae.pubannotation.org/
      image_source: img/service_assets/TextAE.png
      description_jp:
      description_en:
    - id: PubDictionaries
      url: http://pubdictionaries.org
      image_source: img/service_assets/PubDictionaries.png
      description_jp:
      description_en:
    - id: Allie
      url: http://allie.dbcls.jp/
      image_source: img/service_assets/Allie.png
      description_jp:
      description_en:
    - id: Colil
      url: http://colil.dbcls.jp/
      image_source: img/service_assets/Colil.png
      description_jp:
      description_en:
    - id: inMeXes
      url: https://docman.dbcls.jp/im/
      image_source: img/service_assets/inMeXes.png
      description_jp:
      description_en:
    - id: OntoFinder
      url: http://ontofinder.dbcls.jp/
      image_source: img/service_assets/ontofinder.png
      description_jp:
      description_en:
